# use Lora Model Once
# spacectrl = scribble one

# 1-animation
- domain_lora_scale: 1.0
  adapter_lora_path: "pretrained/animatediff/domain_adopter/v3_sd15_adapter.ckpt"
  dreambooth_path:   ""
  inference_config: "configs/inference/inference-v3.yaml"
  motion_module:    "pretrained/animatediff/motion_module/v3_sd15_mm.ckpt"
  controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
  controlnet_path:   "pretrained/models/sparsectrl/v3_sd15_sparsectrl_rgb.ckpt"
  lora_model_path: "pretrained/loras/Dream_LoRA/toonyou_beta3.safetensors"
  H: 256
  W: 384
  seed: [123,234]
  steps: 25
  guidance_scale: 8.5
  controlnet_image_indexs: [0]
  controlnet_images:
    - "__assets__/demos/image/RealisticVision_firework.png"
    -
  prompt:
    - a girl, seeing front, smiling
    - a girl, seeing front, smiling
  n_prompt:
    - "worst quality, low quality, letterboxed"