# 1-animation
- domain_lora_scale: 1.0
  # domain adopter
  adapter_lora_path: "pretrained/animatediff/domain_adopter/v3_sd15_adapter.ckpt"
  dreambooth_path:   ""
  inference_config: "configs/inference/inference-v3.yaml"
  # motion module
  motion_module: "pretrained/animatediff/motion_module/mm_sd_v15_v2.ckpt"
  # controlnet config and the pretraine path
  # (1) make controlnet model with config
  # (2) loading pretrained weight
  controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
  controlnet_path:   "pretrained/models/sparsectrl/v3_sd15_sparsectrl_rgb.ckpt" # what is controlnet path ... ?
  controlnet_image_indexs: [0]

  controlnet_images: # there is controlnet_images ...
    - "__assets__/demos/image/swing_baby.png"
  seed: [123]
  steps: 25
  guidance_scale: 8.5
  prompt: # bambababy never ...
    - bambababy is playing in a playground
    - bambababy is playing in a playground
    - bambababy is playing in a playground
  n_prompt:
    - "worst quality, low quality, letterboxed"
