# use Lora Model Once
# spacectrl = scribble one
#lora_model_path: "pretrained/loras/DreamBooth_LoRA/toonyou_beta3.safetensors"
# 1-animation

- domain_lora_scale: 1.0
  # domain adopter
  adapter_lora_path: "pretrained/animatediff/domain_adopter/v3_sd15_adapter.ckpt"
  dreambooth_path:   ""
  inference_config: "configs/inference/inference-v3.yaml"
  # motion module
  motion_module:    "pretrained/animatediff/motion_module/v2_lora_ZoomIn.ckpt" # only motion module (not motion_lora)
  # controlnet config and the pretraine path
  controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
  controlnet_path:   "pretrained/models/sparsectrl/v3_sd15_sparsectrl_rgb.ckpt"
  controlnet_image_indexs: [0]
  controlnet_images: # there is controlnet_images ...
    - "__assets__/demos/image/swing_baby.png"
  H: 512
  W: 300
  seed: [123]
  steps: 25
  guidance_scale: 8.5
  prompt:
    - bambababy is playing in a playground
    - bambababy is playing on the swings
    - bambababy is having big smile
  n_prompt:
    - "worst quality, low quality, letterboxed"
