image_finetune: true
name: image_finetune
use_wandb: false
launcher: pytorch
output_dir: outputs_sy\image_finetune-2024-05-06T23-09-29
pretrained_model_path: models/StableDiffusion/stable-diffusion-v1-5
train_data:
  csv_path: /datasets/webvid/results_2M_val.csv
  video_folder: /datasets/webvid/results_2M_val.csv
  sample_size: 256
validation_data:
  prompts:
  - Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and
    shadow deep canyons.
  - A drone view of celebration with Christma tree and fireworks, starry sky - background.
  - Robot dancing in times square.
  - Pacific coast, carmel by the sea ocean and waves.
  num_inference_steps: 25
  guidance_scale: 8.0
cfg_random_null_text: true
cfg_random_null_text_ratio: 0.1
unet_checkpoint_path: ''
unet_additional_kwargs: {}
ema_decay: 0.9999
noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: scaled_linear
  steps_offset: 1
  clip_sample: false
max_train_epoch: -1
max_train_steps: 100
validation_steps: 5000
validation_steps_tuple:
- 2
- 50
learning_rate: 1.0e-05
scale_lr: false
lr_warmup_steps: 0
lr_scheduler: constant
trainable_modules:
- .
num_workers: 32
train_batch_size: 50
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
gradient_accumulation_steps: 1
gradient_checkpointing: false
checkpointing_epochs: -1
checkpointing_steps: 60
mixed_precision_training: true
enable_xformers_memory_efficient_attention: true
global_seed: 42
is_debug: false
seed: 42
folder_name: image_finetune-2024-05-06T23-09-29
